apiVersion: v1
kind: Service
metadata:
  name: stockwriteoff
spec:
  selector:
    app: stockwriteoff
  ports:
  - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockwriteoff
  labels:
    app: stockwriteoff
spec:
  selector:
    matchLabels:
      app: stockwriteoff
  template:
    metadata:
      labels:
        app: stockwriteoff
    spec:
      containers:
        - name: stockwriteoff
          image: ${registryURL}/h2o.app.stockwriteoff:299
          env:               
            - name: H2OGateWay
              valueFrom:
                configMapKeyRef:
                  name: stockwriteoff
                  key: H2OGateWay                  
            - name: H2OApplicationHost
              valueFrom:
                configMapKeyRef:
                  name: stockwriteoff
                  key: H2OApplicationHost                    
            - name: ListenUrls__0
              valueFrom:
                configMapKeyRef:
                  name: stockwriteoff
                  key: ListenUrls       
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stockwriteoff
data:
  H2OGateWay: 'http://gateway:8080/'
  ListenUrls: 'http://0.0.0.0:8080/'
  H2OApplicationHost: 'http://stockwriteoff:8080'