apiVersion: v1
kind: Service
metadata:
  name: elmar
spec:
  selector:
    app: elmar
  ports:
    - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elmar
  labels:
    app: elmar
spec:
  selector:
    matchLabels:
      app: elmar
  template:
    metadata:
      labels:
        app: elmar
    spec:
      containers:
        - name: elmar
          image: ${registryURL}/h2o.app.elmar:390
          env:
            - name: H2OGateWay
              valueFrom:
                configMapKeyRef:
                  name: elmar
                  key: H2OGateWay
            - name: H2OApplicationHost
              valueFrom:
                configMapKeyRef:
                  name: elmar
                  key: H2OApplicationHost
            - name: ListenUrls__0
              valueFrom:
                configMapKeyRef:
                  name: elmar
                  key: ListenUrls
            - name: LogFileMinLevel
              valueFrom:
                configMapKeyRef:
                  name: elmar
                  key: LogFileMinLevel
            - name: LogFileDirectory
              valueFrom:
                configMapKeyRef:
                  name: elmar
                  key: LogFileDirectory
            - name: GeneralAuthenticationSettingsUiEnabled
              valueFrom:
                configMapKeyRef:
                  name: elmar
                  key: GeneralAuthenticationSettingsUiEnabled
          readinessProbe:
            httpGet:
              path: /api/microservice/health/live
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/microservice/health/live
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elmar
data:
  H2OGateWay: 'http://gateway:8080/'
  ListenUrls: 'http://0.0.0.0:8080/'
  H2OApplicationHost: 'http://elmar:8080'
  LogFileMinLevel: 'Info'
  LogFileDirectory: '/var/log/hop'
  GeneralAuthenticationSettingsUiEnabled: ''
