apiVersion: v1
kind: Service
metadata:
  name: hrreport
spec:
  selector:
    app: hrreport
  ports:
  - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hrreport
  labels:
    app: hrreport
spec:
  selector:
    matchLabels:
      app: hrreport
  template:
    metadata:
      labels:
        app: hrreport
    spec:
      containers:
        - name: hrreport
          image: ${registryURL}/h2o.app.hrreport:76
          env:               
            - name: H2OGateWay
              valueFrom:
                configMapKeyRef:
                  name: hrreport
                  key: H2OGateWay                  
            - name: H2OApplicationHost
              valueFrom:
                configMapKeyRef:
                  name: hrreport
                  key: H2OApplicationHost                    
            - name: ListenUrls__0
              valueFrom:
                configMapKeyRef:
                  name: hrreport
                  key: ListenUrls       
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hrreport
data:
  H2OGateWay: 'http://gateway:8080/'
  ListenUrls: 'http://0.0.0.0:8080/'
  H2OApplicationHost: 'http://hrreport:8080'