apiVersion: v1
kind: Service
metadata:
  name: matressubmit
spec:
  selector:
    app: matressubmit
  ports:
  - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matressubmit
  labels:
    app: matressubmit
spec:
  selector:
    matchLabels:
      app: matressubmit
  template:
    metadata:
      labels:
        app: matressubmit
    spec:
      containers:
        - name: matressubmit
          image: ${registryURL}/h2o.app.matres.submit:277
          env:               
            - name: H2OGateWay
              valueFrom:
                configMapKeyRef:
                  name: matressubmit
                  key: H2OGateWay                  
            - name: H2OApplicationHost
              valueFrom:
                configMapKeyRef:
                  name: matressubmit
                  key: H2OApplicationHost                    
            - name: ListenUrls__0
              valueFrom:
                configMapKeyRef:
                  name: matressubmit
                  key: ListenUrls       
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: matressubmit
data:
  H2OGateWay: 'http://gateway:8080/'
  ListenUrls: 'http://0.0.0.0:8080/'
  H2OApplicationHost: 'http://matressubmit:8080'