apiVersion: v1
kind: Service
metadata:
  name: training
spec:
  selector:
    app: training
  ports:
  - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: training
  labels:
    app: training
spec:
  selector:
    matchLabels:
      app: training
  template:
    metadata:
      labels:
        app: training
    spec:
      containers:
        - name: training
          image: ${registryURL}/h2o.app.training:522
          env:               
            - name: H2OGateWay
              valueFrom:
                configMapKeyRef:
                  name: training
                  key: H2OGateWay                  
            - name: H2OApplicationHost
              valueFrom:
                configMapKeyRef:
                  name: training
                  key: H2OApplicationHost                    
            - name: ListenUrls__0
              valueFrom:
                configMapKeyRef:
                  name: training
                  key: ListenUrls                    
            - name: LogFileMinLevel
              valueFrom:
                configMapKeyRef:
                  name: training
                  key: LogFileMinLevel                    
            - name: LogFileDirectory
              valueFrom:
                configMapKeyRef:
                  name: training
                  key: LogFileDirectory        
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: training
data:
  H2OGateWay: 'http://gateway:8080/'
  ListenUrls: 'http://0.0.0.0:8080/'
  H2OApplicationHost: 'http://training:8080'
  LogFileMinLevel: 'Info'
  LogFileDirectory: '/var/log/hop'