apiVersion: v1
kind: Service
metadata:
  name: matreshistorylist
spec:
  selector:
    app: matreshistorylist
  ports:
  - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matreshistorylist
  labels:
    app: matreshistorylist
spec:
  selector:
    matchLabels:
      app: matreshistorylist
  template:
    metadata:
      labels:
        app: matreshistorylist
    spec:
      containers:
        - name: matreshistorylist
          image: ${registryURL}/h2o.app.matres.historylist:221
          env:               
            - name: H2OGateWay
              valueFrom:
                configMapKeyRef:
                  name: matreshistorylist
                  key: H2OGateWay                  
            - name: H2OApplicationHost
              valueFrom:
                configMapKeyRef:
                  name: matreshistorylist
                  key: H2OApplicationHost                    
            - name: ListenUrls__0
              valueFrom:
                configMapKeyRef:
                  name: matreshistorylist
                  key: ListenUrls       
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: matreshistorylist
data:
  H2OGateWay: 'http://gateway:8080/'
  ListenUrls: 'http://0.0.0.0:8080/'
  H2OApplicationHost: 'http://matreshistorylist:8080'