apiVersion: v1
kind: Service
metadata:
  name: vacation
spec:
  selector:
    app: vacation
  ports:
    - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vacation
  labels:
    app: vacation
spec:
  selector:
    matchLabels:
      app: vacation
  template:
    metadata:
      labels:
        app: vacation
    spec:
      containers:
        - name: vacation
          image: ${registryURL}/h2o.app.vacation:471
          env:
            - name: H2OGateWay
              valueFrom:
                configMapKeyRef:
                  name: vacation
                  key: H2OGateWay
            - name: H2OApplicationHost
              valueFrom:
                configMapKeyRef:
                  name: vacation
                  key: H2OApplicationHost
            - name: ListenUrls__0
              valueFrom:
                configMapKeyRef:
                  name: vacation
                  key: ListenUrls
            - name: LogFileMinLevel
              valueFrom:
                configMapKeyRef:
                  name: vacation
                  key: LogFileMinLevel
            - name: LogFileDirectory
              valueFrom:
                configMapKeyRef:
                  name: vacation
                  key: LogFileDirectory
          readinessProbe:
            httpGet:
              path: /api/microservice/health/live
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/microservice/health/live
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vacation
data:
  H2OGateWay: 'http://gateway:8080/'
  ListenUrls: 'http://0.0.0.0:8080/'
  H2OApplicationHost: 'http://vacation:8080'
  LogFileMinLevel: 'Info'
  LogFileDirectory: '/var/log/hop'
