apiVersion: v1
kind: Service
metadata:
  name: absencecalendar
spec:
  selector:
    app: absencecalendar
  ports:
  - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: absencecalendar
  labels:
    app: absencecalendar
spec:
  selector:
    matchLabels:
      app: absencecalendar
  template:
    metadata:
      labels:
        app: absencecalendar
    spec:
      containers:
        - name: absencecalendar
          image: /h2o.app.absencecalendar:978
          env:               
            - name: H2OGateWay
              valueFrom:
                configMapKeyRef:
                  name: absencecalendar
                  key: H2OGateWay                  
            - name: H2OApplicationHost
              valueFrom:
                configMapKeyRef:
                  name: absencecalendar
                  key: H2OApplicationHost                    
            - name: ListenUrls__0
              valueFrom:
                configMapKeyRef:
                  name: absencecalendar
                  key: ListenUrls                        
            - name: LogFileMinLevel
              valueFrom:
                configMapKeyRef:
                  name: absencecalendar
                  key: LogFileMinLevel                    
            - name: LogFileDirectory
              valueFrom:
                configMapKeyRef:
                  name: absencecalendar
                  key: LogFileDirectory     
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: absencecalendar
data:
  H2OGateWay: 'http://gateway:8080/'
  ListenUrls: 'http://0.0.0.0:8080/'
  H2OApplicationHost: 'http://absencecalendar:8080'
  LogFileMinLevel: 'Info'
  LogFileDirectory: '/var/log/hop'