apiVersion: v1
kind: Service
metadata:
  name: clientapplications
spec:
  selector:
    app: clientapplications
  ports:
  - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientapplications
  labels:
    app: clientapplications
spec:
  selector:
    matchLabels:
      app: clientapplications
  template:
    metadata:
      labels:
        app: clientapplications
    spec:
      containers:
        - name: clientapplications
          image: /h2o.app.clientapplications:227
          env:               
            - name: H2OGateWay
              valueFrom:
                configMapKeyRef:
                  name: clientapplications
                  key: H2OGateWay                  
            - name: H2OApplicationHost
              valueFrom:
                configMapKeyRef:
                  name: clientapplications
                  key: H2OApplicationHost                    
            - name: ListenUrls__0
              valueFrom:
                configMapKeyRef:
                  name: clientapplications
                  key: ListenUrls                     
            - name: LogFileMinLevel
              valueFrom:
                configMapKeyRef:
                  name: clientapplications
                  key: LogFileMinLevel                    
            - name: LogFileDirectory
              valueFrom:
                configMapKeyRef:
                  name: clientapplications
                  key: LogFileDirectory         
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clientapplications
data:
  H2OGateWay: 'http://gateway:8080/'
  ListenUrls: 'http://0.0.0.0:8080/'
  H2OApplicationHost: 'http://clientapplications:8080'
  LogFileMinLevel: 'Info'
  LogFileDirectory: '/var/log/hop'