apiVersion: v1
kind: Service
metadata:
  name: task
spec:
  selector:
    app: task
  ports:
  - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task
  labels:
    app: task
spec:
  selector:
    matchLabels:
      app: task
  template:
    metadata:
      labels:
        app: task
    spec:
      containers:
        - name: task
          image: ${registryURL}/h2o.app.task:408
          env:               
            - name: H2OGateWay
              valueFrom:
                configMapKeyRef:
                  name: task
                  key: H2OGateWay                  
            - name: H2OApplicationHost
              valueFrom:
                configMapKeyRef:
                  name: task
                  key: H2OApplicationHost                    
            - name: ListenUrls__0
              valueFrom:
                configMapKeyRef:
                  name: task
                  key: ListenUrls       
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: task
data:
  H2OGateWay: 'http://gateway:8080/'
  ListenUrls: 'http://0.0.0.0:8080/'
  H2OApplicationHost: 'http://task:8080'